setup() {
    load 'test_helper/bats-support/load'
    load 'test_helper/bats-assert/load'
    # ... the remaining setup is unchanged

    # get the containing directory of this file
    # use $BATS_TEST_FILENAME instead of ${BASH_SOURCE[0]} or $0,
    # as those will point to the bats executable's location or the preprocessed file respectively
    DIR="$( cd "$( dirname "$BATS_TEST_FILENAME" )" >/dev/null 2>&1 && pwd )"
    # make executables in src/ visible to PATH
    PATH="$DIR/../src:$PATH"
}

@test "'' does not match" {
    run bash -c './_build/default/bin/turing run our-machines/02n_utm.json "E~E{[0P>0][_H<y]}P{[0E>0][_H<n]}&" | cat -e'
    assert_output 'Interpreter starting...$
[<E>~E{[0P>0][_H<y]}P{[0E>0][_H<n]}&] (retrieve_initial_state, E) -> (go-to-input-start-for_E, E, right)$
[E<~>E{[0P>0][_H<y]}P{[0E>0][_H<n]}&] (go-to-input-start-for_E, ~) -> (go-to-input-start-for_E, ~, right)$
[E~<E>{[0P>0][_H<y]}P{[0E>0][_H<n]}&] (go-to-input-start-for_E, E) -> (go-to-input-start-for_E, E, right)$
[E~E<{>[0P>0][_H<y]}P{[0E>0][_H<n]}&] (go-to-input-start-for_E, {) -> (go-to-input-start-for_E, {, right)$
[E~E{<[>0P>0][_H<y]}P{[0E>0][_H<n]}&] (go-to-input-start-for_E, [) -> (go-to-input-start-for_E, [, right)$
[E~E{[<0>P>0][_H<y]}P{[0E>0][_H<n]}&] (go-to-input-start-for_E, 0) -> (go-to-input-start-for_E, 0, right)$
[E~E{[0<P>>0][_H<y]}P{[0E>0][_H<n]}&] (go-to-input-start-for_E, P) -> (go-to-input-start-for_E, P, right)$
[E~E{[0P<>>0][_H<y]}P{[0E>0][_H<n]}&] (go-to-input-start-for_E, >) -> (go-to-input-start-for_E, >, right)$
[E~E{[0P><0>][_H<y]}P{[0E>0][_H<n]}&] (go-to-input-start-for_E, 0) -> (go-to-input-start-for_E, 0, right)$
[E~E{[0P>0<]>[_H<y]}P{[0E>0][_H<n]}&] (go-to-input-start-for_E, ]) -> (go-to-input-start-for_E, ], right)$
[E~E{[0P>0]<[>_H<y]}P{[0E>0][_H<n]}&] (go-to-input-start-for_E, [) -> (go-to-input-start-for_E, [, right)$
[E~E{[0P>0][<_>H<y]}P{[0E>0][_H<n]}&] (go-to-input-start-for_E, _) -> (go-to-input-start-for_E, _, right)$
[E~E{[0P>0][_<H><y]}P{[0E>0][_H<n]}&] (go-to-input-start-for_E, H) -> (go-to-input-start-for_E, H, right)$
[E~E{[0P>0][_H<<>y]}P{[0E>0][_H<n]}&] (go-to-input-start-for_E, <) -> (go-to-input-start-for_E, <, right)$
[E~E{[0P>0][_H<<y>]}P{[0E>0][_H<n]}&] (go-to-input-start-for_E, y) -> (go-to-input-start-for_E, y, right)$
[E~E{[0P>0][_H<y<]>}P{[0E>0][_H<n]}&] (go-to-input-start-for_E, ]) -> (go-to-input-start-for_E, ], right)$
[E~E{[0P>0][_H<y]<}>P{[0E>0][_H<n]}&] (go-to-input-start-for_E, }) -> (go-to-input-start-for_E, }, right)$
[E~E{[0P>0][_H<y]}<P>{[0E>0][_H<n]}&] (go-to-input-start-for_E, P) -> (go-to-input-start-for_E, P, right)$
[E~E{[0P>0][_H<y]}P<{>[0E>0][_H<n]}&] (go-to-input-start-for_E, {) -> (go-to-input-start-for_E, {, right)$
[E~E{[0P>0][_H<y]}P{<[>0E>0][_H<n]}&] (go-to-input-start-for_E, [) -> (go-to-input-start-for_E, [, right)$
[E~E{[0P>0][_H<y]}P{[<0>E>0][_H<n]}&] (go-to-input-start-for_E, 0) -> (go-to-input-start-for_E, 0, right)$
[E~E{[0P>0][_H<y]}P{[0<E>>0][_H<n]}&] (go-to-input-start-for_E, E) -> (go-to-input-start-for_E, E, right)$
[E~E{[0P>0][_H<y]}P{[0E<>>0][_H<n]}&] (go-to-input-start-for_E, >) -> (go-to-input-start-for_E, >, right)$
[E~E{[0P>0][_H<y]}P{[0E><0>][_H<n]}&] (go-to-input-start-for_E, 0) -> (go-to-input-start-for_E, 0, right)$
[E~E{[0P>0][_H<y]}P{[0E>0<]>[_H<n]}&] (go-to-input-start-for_E, ]) -> (go-to-input-start-for_E, ], right)$
[E~E{[0P>0][_H<y]}P{[0E>0]<[>_H<n]}&] (go-to-input-start-for_E, [) -> (go-to-input-start-for_E, [, right)$
[E~E{[0P>0][_H<y]}P{[0E>0][<_>H<n]}&] (go-to-input-start-for_E, _) -> (go-to-input-start-for_E, _, right)$
[E~E{[0P>0][_H<y]}P{[0E>0][_<H><n]}&] (go-to-input-start-for_E, H) -> (go-to-input-start-for_E, H, right)$
[E~E{[0P>0][_H<y]}P{[0E>0][_H<<>n]}&] (go-to-input-start-for_E, <) -> (go-to-input-start-for_E, <, right)$
[E~E{[0P>0][_H<y]}P{[0E>0][_H<<n>]}&] (go-to-input-start-for_E, n) -> (go-to-input-start-for_E, n, right)$
[E~E{[0P>0][_H<y]}P{[0E>0][_H<n<]>}&] (go-to-input-start-for_E, ]) -> (go-to-input-start-for_E, ], right)$
[E~E{[0P>0][_H<y]}P{[0E>0][_H<n]<}>&] (go-to-input-start-for_E, }) -> (go-to-input-start-for_E, }, right)$
[E~E{[0P>0][_H<y]}P{[0E>0][_H<n]}<&>] (go-to-input-start-for_E, &) -> (read-tape-for_E, &, right)$
[E~E{[0P>0][_H<y]}P{[0E>0][_H<n]}&<.>] (read-tape-for_E, .) -> (scanleft-to-states-declaration-for_E(.), ^, left)$
[E~E{[0P>0][_H<y]}P{[0E>0][_H<n]}<&>^] (scanleft-to-states-declaration-for_E(.), &) -> (scanleft-to-states-declaration-for_E(.), &, left)$
[E~E{[0P>0][_H<y]}P{[0E>0][_H<n]<}>&^] (scanleft-to-states-declaration-for_E(.), }) -> (scanleft-to-states-declaration-for_E(.), }, left)$
[E~E{[0P>0][_H<y]}P{[0E>0][_H<n<]>}&^] (scanleft-to-states-declaration-for_E(.), ]) -> (scanleft-to-states-declaration-for_E(.), ], left)$
[E~E{[0P>0][_H<y]}P{[0E>0][_H<<n>]}&^] (scanleft-to-states-declaration-for_E(.), n) -> (scanleft-to-states-declaration-for_E(.), n, left)$
[E~E{[0P>0][_H<y]}P{[0E>0][_H<<>n]}&^] (scanleft-to-states-declaration-for_E(.), <) -> (scanleft-to-states-declaration-for_E(.), <, left)$
[E~E{[0P>0][_H<y]}P{[0E>0][_<H><n]}&^] (scanleft-to-states-declaration-for_E(.), H) -> (scanleft-to-states-declaration-for_E(.), H, left)$
[E~E{[0P>0][_H<y]}P{[0E>0][<_>H<n]}&^] (scanleft-to-states-declaration-for_E(.), _) -> (scanleft-to-states-declaration-for_E(.), _, left)$
[E~E{[0P>0][_H<y]}P{[0E>0]<[>_H<n]}&^] (scanleft-to-states-declaration-for_E(.), [) -> (scanleft-to-states-declaration-for_E(.), [, left)$
[E~E{[0P>0][_H<y]}P{[0E>0<]>[_H<n]}&^] (scanleft-to-states-declaration-for_E(.), ]) -> (scanleft-to-states-declaration-for_E(.), ], left)$
[E~E{[0P>0][_H<y]}P{[0E><0>][_H<n]}&^] (scanleft-to-states-declaration-for_E(.), 0) -> (scanleft-to-states-declaration-for_E(.), 0, left)$
[E~E{[0P>0][_H<y]}P{[0E<>>0][_H<n]}&^] (scanleft-to-states-declaration-for_E(.), >) -> (scanleft-to-states-declaration-for_E(.), >, left)$
[E~E{[0P>0][_H<y]}P{[0<E>>0][_H<n]}&^] (scanleft-to-states-declaration-for_E(.), E) -> (scanleft-to-states-declaration-for_E(.), E, left)$
[E~E{[0P>0][_H<y]}P{[<0>E>0][_H<n]}&^] (scanleft-to-states-declaration-for_E(.), 0) -> (scanleft-to-states-declaration-for_E(.), 0, left)$
[E~E{[0P>0][_H<y]}P{<[>0E>0][_H<n]}&^] (scanleft-to-states-declaration-for_E(.), [) -> (scanleft-to-states-declaration-for_E(.), [, left)$
[E~E{[0P>0][_H<y]}P<{>[0E>0][_H<n]}&^] (scanleft-to-states-declaration-for_E(.), {) -> (scanleft-to-states-declaration-for_E(.), {, left)$
[E~E{[0P>0][_H<y]}<P>{[0E>0][_H<n]}&^] (scanleft-to-states-declaration-for_E(.), P) -> (scanleft-to-states-declaration-for_E(.), P, left)$
[E~E{[0P>0][_H<y]<}>P{[0E>0][_H<n]}&^] (scanleft-to-states-declaration-for_E(.), }) -> (scanleft-to-states-declaration-for_E(.), }, left)$
[E~E{[0P>0][_H<y<]>}P{[0E>0][_H<n]}&^] (scanleft-to-states-declaration-for_E(.), ]) -> (scanleft-to-states-declaration-for_E(.), ], left)$
[E~E{[0P>0][_H<<y>]}P{[0E>0][_H<n]}&^] (scanleft-to-states-declaration-for_E(.), y) -> (scanleft-to-states-declaration-for_E(.), y, left)$
[E~E{[0P>0][_H<<>y]}P{[0E>0][_H<n]}&^] (scanleft-to-states-declaration-for_E(.), <) -> (scanleft-to-states-declaration-for_E(.), <, left)$
[E~E{[0P>0][_<H><y]}P{[0E>0][_H<n]}&^] (scanleft-to-states-declaration-for_E(.), H) -> (scanleft-to-states-declaration-for_E(.), H, left)$
[E~E{[0P>0][<_>H<y]}P{[0E>0][_H<n]}&^] (scanleft-to-states-declaration-for_E(.), _) -> (scanleft-to-states-declaration-for_E(.), _, left)$
[E~E{[0P>0]<[>_H<y]}P{[0E>0][_H<n]}&^] (scanleft-to-states-declaration-for_E(.), [) -> (scanleft-to-states-declaration-for_E(.), [, left)$
[E~E{[0P>0<]>[_H<y]}P{[0E>0][_H<n]}&^] (scanleft-to-states-declaration-for_E(.), ]) -> (scanleft-to-states-declaration-for_E(.), ], left)$
[E~E{[0P><0>][_H<y]}P{[0E>0][_H<n]}&^] (scanleft-to-states-declaration-for_E(.), 0) -> (scanleft-to-states-declaration-for_E(.), 0, left)$
[E~E{[0P<>>0][_H<y]}P{[0E>0][_H<n]}&^] (scanleft-to-states-declaration-for_E(.), >) -> (scanleft-to-states-declaration-for_E(.), >, left)$
[E~E{[0<P>>0][_H<y]}P{[0E>0][_H<n]}&^] (scanleft-to-states-declaration-for_E(.), P) -> (scanleft-to-states-declaration-for_E(.), P, left)$
[E~E{[<0>P>0][_H<y]}P{[0E>0][_H<n]}&^] (scanleft-to-states-declaration-for_E(.), 0) -> (scanleft-to-states-declaration-for_E(.), 0, left)$
[E~E{<[>0P>0][_H<y]}P{[0E>0][_H<n]}&^] (scanleft-to-states-declaration-for_E(.), [) -> (scanleft-to-states-declaration-for_E(.), [, left)$
[E~E<{>[0P>0][_H<y]}P{[0E>0][_H<n]}&^] (scanleft-to-states-declaration-for_E(.), {) -> (scanleft-to-states-declaration-for_E(.), {, left)$
[E~<E>{[0P>0][_H<y]}P{[0E>0][_H<n]}&^] (scanleft-to-states-declaration-for_E(.), E) -> (scanleft-to-states-declaration-for_E(.), E, left)$
[E<~>E{[0P>0][_H<y]}P{[0E>0][_H<n]}&^] (scanleft-to-states-declaration-for_E(.), ~) -> (find-state_E(.), ~, right)$
[E~<E>{[0P>0][_H<y]}P{[0E>0][_H<n]}&^] (find-state_E(.), E) -> (find-state-transition-for_E(.), E, right)$
[E~E<{>[0P>0][_H<y]}P{[0E>0][_H<n]}&^] (find-state-transition-for_E(.), {) -> (find-state-transition-for_E(.), {, right)$
[E~E{<[>0P>0][_H<y]}P{[0E>0][_H<n]}&^] (find-state-transition-for_E(.), [) -> (find-state-transition-for_E(.), [, right)$
[E~E{[<0>P>0][_H<y]}P{[0E>0][_H<n]}&^] (find-state-transition-for_E(.), 0) -> (scanright-to-next-state-transition_E(.), 0, right)$
[E~E{[0<P>>0][_H<y]}P{[0E>0][_H<n]}&^] (scanright-to-next-state-transition_E(.), P) -> (scanright-to-next-state-transition_E(.), P, right)$
[E~E{[0P<>>0][_H<y]}P{[0E>0][_H<n]}&^] (scanright-to-next-state-transition_E(.), >) -> (scanright-to-next-state-transition_E(.), >, right)$
[E~E{[0P><0>][_H<y]}P{[0E>0][_H<n]}&^] (scanright-to-next-state-transition_E(.), 0) -> (scanright-to-next-state-transition_E(.), 0, right)$
[E~E{[0P>0<]>[_H<y]}P{[0E>0][_H<n]}&^] (scanright-to-next-state-transition_E(.), ]) -> (find-state-transition-for_E(.), ], right)$
[E~E{[0P>0]<[>_H<y]}P{[0E>0][_H<n]}&^] (find-state-transition-for_E(.), [) -> (find-state-transition-for_E(.), [, right)$
[E~E{[0P>0][<_>H<y]}P{[0E>0][_H<n]}&^] (find-state-transition-for_E(.), _) -> (retrieve-transition-to_state, _, right)$
[E~E{[0P>0][_<H><y]}P{[0E>0][_H<n]}&^] (retrieve-transition-to_state, H) -> (retrieve-transition-H_action, H, right)$
[E~E{[0P>0][_H<<>y]}P{[0E>0][_H<n]}&^] (retrieve-transition-H_action, <) -> (retrieve-transition-H_<_write, <, right)$
[E~E{[0P>0][_H<<y>]}P{[0E>0][_H<n]}&^] (retrieve-transition-H_<_write, y) -> (execute-transition-H_<_y, y, right)$
[E~E{[0P>0][_H<y<]>}P{[0E>0][_H<n]}&^] (execute-transition-H_<_y, ]) -> (execute-transition-H_<_y, ], right)$
[E~E{[0P>0][_H<y]<}>P{[0E>0][_H<n]}&^] (execute-transition-H_<_y, }) -> (execute-transition-H_<_y, }, right)$
[E~E{[0P>0][_H<y]}<P>{[0E>0][_H<n]}&^] (execute-transition-H_<_y, P) -> (execute-transition-H_<_y, P, right)$
[E~E{[0P>0][_H<y]}P<{>[0E>0][_H<n]}&^] (execute-transition-H_<_y, {) -> (execute-transition-H_<_y, {, right)$
[E~E{[0P>0][_H<y]}P{<[>0E>0][_H<n]}&^] (execute-transition-H_<_y, [) -> (execute-transition-H_<_y, [, right)$
[E~E{[0P>0][_H<y]}P{[<0>E>0][_H<n]}&^] (execute-transition-H_<_y, 0) -> (execute-transition-H_<_y, 0, right)$
[E~E{[0P>0][_H<y]}P{[0<E>>0][_H<n]}&^] (execute-transition-H_<_y, E) -> (execute-transition-H_<_y, E, right)$
[E~E{[0P>0][_H<y]}P{[0E<>>0][_H<n]}&^] (execute-transition-H_<_y, >) -> (execute-transition-H_<_y, >, right)$
[E~E{[0P>0][_H<y]}P{[0E><0>][_H<n]}&^] (execute-transition-H_<_y, 0) -> (execute-transition-H_<_y, 0, right)$
[E~E{[0P>0][_H<y]}P{[0E>0<]>[_H<n]}&^] (execute-transition-H_<_y, ]) -> (execute-transition-H_<_y, ], right)$
[E~E{[0P>0][_H<y]}P{[0E>0]<[>_H<n]}&^] (execute-transition-H_<_y, [) -> (execute-transition-H_<_y, [, right)$
[E~E{[0P>0][_H<y]}P{[0E>0][<_>H<n]}&^] (execute-transition-H_<_y, _) -> (execute-transition-H_<_y, _, right)$
[E~E{[0P>0][_H<y]}P{[0E>0][_<H><n]}&^] (execute-transition-H_<_y, H) -> (execute-transition-H_<_y, H, right)$
[E~E{[0P>0][_H<y]}P{[0E>0][_H<<>n]}&^] (execute-transition-H_<_y, <) -> (execute-transition-H_<_y, <, right)$
[E~E{[0P>0][_H<y]}P{[0E>0][_H<<n>]}&^] (execute-transition-H_<_y, n) -> (execute-transition-H_<_y, n, right)$
[E~E{[0P>0][_H<y]}P{[0E>0][_H<n<]>}&^] (execute-transition-H_<_y, ]) -> (execute-transition-H_<_y, ], right)$
[E~E{[0P>0][_H<y]}P{[0E>0][_H<n]<}>&^] (execute-transition-H_<_y, }) -> (execute-transition-H_<_y, }, right)$
[E~E{[0P>0][_H<y]}P{[0E>0][_H<n]}<&>^] (execute-transition-H_<_y, &) -> (execute-transition-H_<_y, &, right)$
[E~E{[0P>0][_H<y]}P{[0E>0][_H<n]}&<^>] (execute-transition-H_<_y, ^) -> (HALT, y, left)$
[E~E{[0P>0][_H<y]}P{[0E>0][_H<n]}<&>y] Final state reached !$
Interpreter closing...$'
}


@test "'0' does not match" {
    run bash -c './_build/default/bin/turing run our-machines/02n_utm.json "E~E{[0P>0][_H<y]}P{[0E>0][_H<n]}&0" | cat -e'
    assert_output 'Interpreter starting...$
[<E>~E{[0P>0][_H<y]}P{[0E>0][_H<n]}&0] (retrieve_initial_state, E) -> (go-to-input-start-for_E, E, right)$
[E<~>E{[0P>0][_H<y]}P{[0E>0][_H<n]}&0] (go-to-input-start-for_E, ~) -> (go-to-input-start-for_E, ~, right)$
[E~<E>{[0P>0][_H<y]}P{[0E>0][_H<n]}&0] (go-to-input-start-for_E, E) -> (go-to-input-start-for_E, E, right)$
[E~E<{>[0P>0][_H<y]}P{[0E>0][_H<n]}&0] (go-to-input-start-for_E, {) -> (go-to-input-start-for_E, {, right)$
[E~E{<[>0P>0][_H<y]}P{[0E>0][_H<n]}&0] (go-to-input-start-for_E, [) -> (go-to-input-start-for_E, [, right)$
[E~E{[<0>P>0][_H<y]}P{[0E>0][_H<n]}&0] (go-to-input-start-for_E, 0) -> (go-to-input-start-for_E, 0, right)$
[E~E{[0<P>>0][_H<y]}P{[0E>0][_H<n]}&0] (go-to-input-start-for_E, P) -> (go-to-input-start-for_E, P, right)$
[E~E{[0P<>>0][_H<y]}P{[0E>0][_H<n]}&0] (go-to-input-start-for_E, >) -> (go-to-input-start-for_E, >, right)$
[E~E{[0P><0>][_H<y]}P{[0E>0][_H<n]}&0] (go-to-input-start-for_E, 0) -> (go-to-input-start-for_E, 0, right)$
[E~E{[0P>0<]>[_H<y]}P{[0E>0][_H<n]}&0] (go-to-input-start-for_E, ]) -> (go-to-input-start-for_E, ], right)$
[E~E{[0P>0]<[>_H<y]}P{[0E>0][_H<n]}&0] (go-to-input-start-for_E, [) -> (go-to-input-start-for_E, [, right)$
[E~E{[0P>0][<_>H<y]}P{[0E>0][_H<n]}&0] (go-to-input-start-for_E, _) -> (go-to-input-start-for_E, _, right)$
[E~E{[0P>0][_<H><y]}P{[0E>0][_H<n]}&0] (go-to-input-start-for_E, H) -> (go-to-input-start-for_E, H, right)$
[E~E{[0P>0][_H<<>y]}P{[0E>0][_H<n]}&0] (go-to-input-start-for_E, <) -> (go-to-input-start-for_E, <, right)$
[E~E{[0P>0][_H<<y>]}P{[0E>0][_H<n]}&0] (go-to-input-start-for_E, y) -> (go-to-input-start-for_E, y, right)$
[E~E{[0P>0][_H<y<]>}P{[0E>0][_H<n]}&0] (go-to-input-start-for_E, ]) -> (go-to-input-start-for_E, ], right)$
[E~E{[0P>0][_H<y]<}>P{[0E>0][_H<n]}&0] (go-to-input-start-for_E, }) -> (go-to-input-start-for_E, }, right)$
[E~E{[0P>0][_H<y]}<P>{[0E>0][_H<n]}&0] (go-to-input-start-for_E, P) -> (go-to-input-start-for_E, P, right)$
[E~E{[0P>0][_H<y]}P<{>[0E>0][_H<n]}&0] (go-to-input-start-for_E, {) -> (go-to-input-start-for_E, {, right)$
[E~E{[0P>0][_H<y]}P{<[>0E>0][_H<n]}&0] (go-to-input-start-for_E, [) -> (go-to-input-start-for_E, [, right)$
[E~E{[0P>0][_H<y]}P{[<0>E>0][_H<n]}&0] (go-to-input-start-for_E, 0) -> (go-to-input-start-for_E, 0, right)$
[E~E{[0P>0][_H<y]}P{[0<E>>0][_H<n]}&0] (go-to-input-start-for_E, E) -> (go-to-input-start-for_E, E, right)$
[E~E{[0P>0][_H<y]}P{[0E<>>0][_H<n]}&0] (go-to-input-start-for_E, >) -> (go-to-input-start-for_E, >, right)$
[E~E{[0P>0][_H<y]}P{[0E><0>][_H<n]}&0] (go-to-input-start-for_E, 0) -> (go-to-input-start-for_E, 0, right)$
[E~E{[0P>0][_H<y]}P{[0E>0<]>[_H<n]}&0] (go-to-input-start-for_E, ]) -> (go-to-input-start-for_E, ], right)$
[E~E{[0P>0][_H<y]}P{[0E>0]<[>_H<n]}&0] (go-to-input-start-for_E, [) -> (go-to-input-start-for_E, [, right)$
[E~E{[0P>0][_H<y]}P{[0E>0][<_>H<n]}&0] (go-to-input-start-for_E, _) -> (go-to-input-start-for_E, _, right)$
[E~E{[0P>0][_H<y]}P{[0E>0][_<H><n]}&0] (go-to-input-start-for_E, H) -> (go-to-input-start-for_E, H, right)$
[E~E{[0P>0][_H<y]}P{[0E>0][_H<<>n]}&0] (go-to-input-start-for_E, <) -> (go-to-input-start-for_E, <, right)$
[E~E{[0P>0][_H<y]}P{[0E>0][_H<<n>]}&0] (go-to-input-start-for_E, n) -> (go-to-input-start-for_E, n, right)$
[E~E{[0P>0][_H<y]}P{[0E>0][_H<n<]>}&0] (go-to-input-start-for_E, ]) -> (go-to-input-start-for_E, ], right)$
[E~E{[0P>0][_H<y]}P{[0E>0][_H<n]<}>&0] (go-to-input-start-for_E, }) -> (go-to-input-start-for_E, }, right)$
[E~E{[0P>0][_H<y]}P{[0E>0][_H<n]}<&>0] (go-to-input-start-for_E, &) -> (read-tape-for_E, &, right)$
[E~E{[0P>0][_H<y]}P{[0E>0][_H<n]}&<0>] (read-tape-for_E, 0) -> (scanleft-to-states-declaration-for_E(0), ^, left)$
[E~E{[0P>0][_H<y]}P{[0E>0][_H<n]}<&>^] (scanleft-to-states-declaration-for_E(0), &) -> (scanleft-to-states-declaration-for_E(0), &, left)$
[E~E{[0P>0][_H<y]}P{[0E>0][_H<n]<}>&^] (scanleft-to-states-declaration-for_E(0), }) -> (scanleft-to-states-declaration-for_E(0), }, left)$
[E~E{[0P>0][_H<y]}P{[0E>0][_H<n<]>}&^] (scanleft-to-states-declaration-for_E(0), ]) -> (scanleft-to-states-declaration-for_E(0), ], left)$
[E~E{[0P>0][_H<y]}P{[0E>0][_H<<n>]}&^] (scanleft-to-states-declaration-for_E(0), n) -> (scanleft-to-states-declaration-for_E(0), n, left)$
[E~E{[0P>0][_H<y]}P{[0E>0][_H<<>n]}&^] (scanleft-to-states-declaration-for_E(0), <) -> (scanleft-to-states-declaration-for_E(0), <, left)$
[E~E{[0P>0][_H<y]}P{[0E>0][_<H><n]}&^] (scanleft-to-states-declaration-for_E(0), H) -> (scanleft-to-states-declaration-for_E(0), H, left)$
[E~E{[0P>0][_H<y]}P{[0E>0][<_>H<n]}&^] (scanleft-to-states-declaration-for_E(0), _) -> (scanleft-to-states-declaration-for_E(0), _, left)$
[E~E{[0P>0][_H<y]}P{[0E>0]<[>_H<n]}&^] (scanleft-to-states-declaration-for_E(0), [) -> (scanleft-to-states-declaration-for_E(0), [, left)$
[E~E{[0P>0][_H<y]}P{[0E>0<]>[_H<n]}&^] (scanleft-to-states-declaration-for_E(0), ]) -> (scanleft-to-states-declaration-for_E(0), ], left)$
[E~E{[0P>0][_H<y]}P{[0E><0>][_H<n]}&^] (scanleft-to-states-declaration-for_E(0), 0) -> (scanleft-to-states-declaration-for_E(0), 0, left)$
[E~E{[0P>0][_H<y]}P{[0E<>>0][_H<n]}&^] (scanleft-to-states-declaration-for_E(0), >) -> (scanleft-to-states-declaration-for_E(0), >, left)$
[E~E{[0P>0][_H<y]}P{[0<E>>0][_H<n]}&^] (scanleft-to-states-declaration-for_E(0), E) -> (scanleft-to-states-declaration-for_E(0), E, left)$
[E~E{[0P>0][_H<y]}P{[<0>E>0][_H<n]}&^] (scanleft-to-states-declaration-for_E(0), 0) -> (scanleft-to-states-declaration-for_E(0), 0, left)$
[E~E{[0P>0][_H<y]}P{<[>0E>0][_H<n]}&^] (scanleft-to-states-declaration-for_E(0), [) -> (scanleft-to-states-declaration-for_E(0), [, left)$
[E~E{[0P>0][_H<y]}P<{>[0E>0][_H<n]}&^] (scanleft-to-states-declaration-for_E(0), {) -> (scanleft-to-states-declaration-for_E(0), {, left)$
[E~E{[0P>0][_H<y]}<P>{[0E>0][_H<n]}&^] (scanleft-to-states-declaration-for_E(0), P) -> (scanleft-to-states-declaration-for_E(0), P, left)$
[E~E{[0P>0][_H<y]<}>P{[0E>0][_H<n]}&^] (scanleft-to-states-declaration-for_E(0), }) -> (scanleft-to-states-declaration-for_E(0), }, left)$
[E~E{[0P>0][_H<y<]>}P{[0E>0][_H<n]}&^] (scanleft-to-states-declaration-for_E(0), ]) -> (scanleft-to-states-declaration-for_E(0), ], left)$
[E~E{[0P>0][_H<<y>]}P{[0E>0][_H<n]}&^] (scanleft-to-states-declaration-for_E(0), y) -> (scanleft-to-states-declaration-for_E(0), y, left)$
[E~E{[0P>0][_H<<>y]}P{[0E>0][_H<n]}&^] (scanleft-to-states-declaration-for_E(0), <) -> (scanleft-to-states-declaration-for_E(0), <, left)$
[E~E{[0P>0][_<H><y]}P{[0E>0][_H<n]}&^] (scanleft-to-states-declaration-for_E(0), H) -> (scanleft-to-states-declaration-for_E(0), H, left)$
[E~E{[0P>0][<_>H<y]}P{[0E>0][_H<n]}&^] (scanleft-to-states-declaration-for_E(0), _) -> (scanleft-to-states-declaration-for_E(0), _, left)$
[E~E{[0P>0]<[>_H<y]}P{[0E>0][_H<n]}&^] (scanleft-to-states-declaration-for_E(0), [) -> (scanleft-to-states-declaration-for_E(0), [, left)$
[E~E{[0P>0<]>[_H<y]}P{[0E>0][_H<n]}&^] (scanleft-to-states-declaration-for_E(0), ]) -> (scanleft-to-states-declaration-for_E(0), ], left)$
[E~E{[0P><0>][_H<y]}P{[0E>0][_H<n]}&^] (scanleft-to-states-declaration-for_E(0), 0) -> (scanleft-to-states-declaration-for_E(0), 0, left)$
[E~E{[0P<>>0][_H<y]}P{[0E>0][_H<n]}&^] (scanleft-to-states-declaration-for_E(0), >) -> (scanleft-to-states-declaration-for_E(0), >, left)$
[E~E{[0<P>>0][_H<y]}P{[0E>0][_H<n]}&^] (scanleft-to-states-declaration-for_E(0), P) -> (scanleft-to-states-declaration-for_E(0), P, left)$
[E~E{[<0>P>0][_H<y]}P{[0E>0][_H<n]}&^] (scanleft-to-states-declaration-for_E(0), 0) -> (scanleft-to-states-declaration-for_E(0), 0, left)$
[E~E{<[>0P>0][_H<y]}P{[0E>0][_H<n]}&^] (scanleft-to-states-declaration-for_E(0), [) -> (scanleft-to-states-declaration-for_E(0), [, left)$
[E~E<{>[0P>0][_H<y]}P{[0E>0][_H<n]}&^] (scanleft-to-states-declaration-for_E(0), {) -> (scanleft-to-states-declaration-for_E(0), {, left)$
[E~<E>{[0P>0][_H<y]}P{[0E>0][_H<n]}&^] (scanleft-to-states-declaration-for_E(0), E) -> (scanleft-to-states-declaration-for_E(0), E, left)$
[E<~>E{[0P>0][_H<y]}P{[0E>0][_H<n]}&^] (scanleft-to-states-declaration-for_E(0), ~) -> (find-state_E(0), ~, right)$
[E~<E>{[0P>0][_H<y]}P{[0E>0][_H<n]}&^] (find-state_E(0), E) -> (find-state-transition-for_E(0), E, right)$
[E~E<{>[0P>0][_H<y]}P{[0E>0][_H<n]}&^] (find-state-transition-for_E(0), {) -> (find-state-transition-for_E(0), {, right)$
[E~E{<[>0P>0][_H<y]}P{[0E>0][_H<n]}&^] (find-state-transition-for_E(0), [) -> (find-state-transition-for_E(0), [, right)$
[E~E{[<0>P>0][_H<y]}P{[0E>0][_H<n]}&^] (find-state-transition-for_E(0), 0) -> (retrieve-transition-to_state, 0, right)$
[E~E{[0<P>>0][_H<y]}P{[0E>0][_H<n]}&^] (retrieve-transition-to_state, P) -> (retrieve-transition-P_action, P, right)$
[E~E{[0P<>>0][_H<y]}P{[0E>0][_H<n]}&^] (retrieve-transition-P_action, >) -> (retrieve-transition-P_>_write, >, right)$
[E~E{[0P><0>][_H<y]}P{[0E>0][_H<n]}&^] (retrieve-transition-P_>_write, 0) -> (execute-transition-P_>_0, 0, right)$
[E~E{[0P>0<]>[_H<y]}P{[0E>0][_H<n]}&^] (execute-transition-P_>_0, ]) -> (execute-transition-P_>_0, ], right)$
[E~E{[0P>0]<[>_H<y]}P{[0E>0][_H<n]}&^] (execute-transition-P_>_0, [) -> (execute-transition-P_>_0, [, right)$
[E~E{[0P>0][<_>H<y]}P{[0E>0][_H<n]}&^] (execute-transition-P_>_0, _) -> (execute-transition-P_>_0, _, right)$
[E~E{[0P>0][_<H><y]}P{[0E>0][_H<n]}&^] (execute-transition-P_>_0, H) -> (execute-transition-P_>_0, H, right)$
[E~E{[0P>0][_H<<>y]}P{[0E>0][_H<n]}&^] (execute-transition-P_>_0, <) -> (execute-transition-P_>_0, <, right)$
[E~E{[0P>0][_H<<y>]}P{[0E>0][_H<n]}&^] (execute-transition-P_>_0, y) -> (execute-transition-P_>_0, y, right)$
[E~E{[0P>0][_H<y<]>}P{[0E>0][_H<n]}&^] (execute-transition-P_>_0, ]) -> (execute-transition-P_>_0, ], right)$
[E~E{[0P>0][_H<y]<}>P{[0E>0][_H<n]}&^] (execute-transition-P_>_0, }) -> (execute-transition-P_>_0, }, right)$
[E~E{[0P>0][_H<y]}<P>{[0E>0][_H<n]}&^] (execute-transition-P_>_0, P) -> (execute-transition-P_>_0, P, right)$
[E~E{[0P>0][_H<y]}P<{>[0E>0][_H<n]}&^] (execute-transition-P_>_0, {) -> (execute-transition-P_>_0, {, right)$
[E~E{[0P>0][_H<y]}P{<[>0E>0][_H<n]}&^] (execute-transition-P_>_0, [) -> (execute-transition-P_>_0, [, right)$
[E~E{[0P>0][_H<y]}P{[<0>E>0][_H<n]}&^] (execute-transition-P_>_0, 0) -> (execute-transition-P_>_0, 0, right)$
[E~E{[0P>0][_H<y]}P{[0<E>>0][_H<n]}&^] (execute-transition-P_>_0, E) -> (execute-transition-P_>_0, E, right)$
[E~E{[0P>0][_H<y]}P{[0E<>>0][_H<n]}&^] (execute-transition-P_>_0, >) -> (execute-transition-P_>_0, >, right)$
[E~E{[0P>0][_H<y]}P{[0E><0>][_H<n]}&^] (execute-transition-P_>_0, 0) -> (execute-transition-P_>_0, 0, right)$
[E~E{[0P>0][_H<y]}P{[0E>0<]>[_H<n]}&^] (execute-transition-P_>_0, ]) -> (execute-transition-P_>_0, ], right)$
[E~E{[0P>0][_H<y]}P{[0E>0]<[>_H<n]}&^] (execute-transition-P_>_0, [) -> (execute-transition-P_>_0, [, right)$
[E~E{[0P>0][_H<y]}P{[0E>0][<_>H<n]}&^] (execute-transition-P_>_0, _) -> (execute-transition-P_>_0, _, right)$
[E~E{[0P>0][_H<y]}P{[0E>0][_<H><n]}&^] (execute-transition-P_>_0, H) -> (execute-transition-P_>_0, H, right)$
[E~E{[0P>0][_H<y]}P{[0E>0][_H<<>n]}&^] (execute-transition-P_>_0, <) -> (execute-transition-P_>_0, <, right)$
[E~E{[0P>0][_H<y]}P{[0E>0][_H<<n>]}&^] (execute-transition-P_>_0, n) -> (execute-transition-P_>_0, n, right)$
[E~E{[0P>0][_H<y]}P{[0E>0][_H<n<]>}&^] (execute-transition-P_>_0, ]) -> (execute-transition-P_>_0, ], right)$
[E~E{[0P>0][_H<y]}P{[0E>0][_H<n]<}>&^] (execute-transition-P_>_0, }) -> (execute-transition-P_>_0, }, right)$
[E~E{[0P>0][_H<y]}P{[0E>0][_H<n]}<&>^] (execute-transition-P_>_0, &) -> (execute-transition-P_>_0, &, right)$
[E~E{[0P>0][_H<y]}P{[0E>0][_H<n]}&<^>] (execute-transition-P_>_0, ^) -> (read-tape-for_P, 0, right)$
[E~E{[0P>0][_H<y]}P{[0E>0][_H<n]}&0<.>] (read-tape-for_P, .) -> (scanleft-to-states-declaration-for_P(.), ^, left)$
[E~E{[0P>0][_H<y]}P{[0E>0][_H<n]}&<0>^] (scanleft-to-states-declaration-for_P(.), 0) -> (scanleft-to-states-declaration-for_P(.), 0, left)$
[E~E{[0P>0][_H<y]}P{[0E>0][_H<n]}<&>0^] (scanleft-to-states-declaration-for_P(.), &) -> (scanleft-to-states-declaration-for_P(.), &, left)$
[E~E{[0P>0][_H<y]}P{[0E>0][_H<n]<}>&0^] (scanleft-to-states-declaration-for_P(.), }) -> (scanleft-to-states-declaration-for_P(.), }, left)$
[E~E{[0P>0][_H<y]}P{[0E>0][_H<n<]>}&0^] (scanleft-to-states-declaration-for_P(.), ]) -> (scanleft-to-states-declaration-for_P(.), ], left)$
[E~E{[0P>0][_H<y]}P{[0E>0][_H<<n>]}&0^] (scanleft-to-states-declaration-for_P(.), n) -> (scanleft-to-states-declaration-for_P(.), n, left)$
[E~E{[0P>0][_H<y]}P{[0E>0][_H<<>n]}&0^] (scanleft-to-states-declaration-for_P(.), <) -> (scanleft-to-states-declaration-for_P(.), <, left)$
[E~E{[0P>0][_H<y]}P{[0E>0][_<H><n]}&0^] (scanleft-to-states-declaration-for_P(.), H) -> (scanleft-to-states-declaration-for_P(.), H, left)$
[E~E{[0P>0][_H<y]}P{[0E>0][<_>H<n]}&0^] (scanleft-to-states-declaration-for_P(.), _) -> (scanleft-to-states-declaration-for_P(.), _, left)$
[E~E{[0P>0][_H<y]}P{[0E>0]<[>_H<n]}&0^] (scanleft-to-states-declaration-for_P(.), [) -> (scanleft-to-states-declaration-for_P(.), [, left)$
[E~E{[0P>0][_H<y]}P{[0E>0<]>[_H<n]}&0^] (scanleft-to-states-declaration-for_P(.), ]) -> (scanleft-to-states-declaration-for_P(.), ], left)$
[E~E{[0P>0][_H<y]}P{[0E><0>][_H<n]}&0^] (scanleft-to-states-declaration-for_P(.), 0) -> (scanleft-to-states-declaration-for_P(.), 0, left)$
[E~E{[0P>0][_H<y]}P{[0E<>>0][_H<n]}&0^] (scanleft-to-states-declaration-for_P(.), >) -> (scanleft-to-states-declaration-for_P(.), >, left)$
[E~E{[0P>0][_H<y]}P{[0<E>>0][_H<n]}&0^] (scanleft-to-states-declaration-for_P(.), E) -> (scanleft-to-states-declaration-for_P(.), E, left)$
[E~E{[0P>0][_H<y]}P{[<0>E>0][_H<n]}&0^] (scanleft-to-states-declaration-for_P(.), 0) -> (scanleft-to-states-declaration-for_P(.), 0, left)$
[E~E{[0P>0][_H<y]}P{<[>0E>0][_H<n]}&0^] (scanleft-to-states-declaration-for_P(.), [) -> (scanleft-to-states-declaration-for_P(.), [, left)$
[E~E{[0P>0][_H<y]}P<{>[0E>0][_H<n]}&0^] (scanleft-to-states-declaration-for_P(.), {) -> (scanleft-to-states-declaration-for_P(.), {, left)$
[E~E{[0P>0][_H<y]}<P>{[0E>0][_H<n]}&0^] (scanleft-to-states-declaration-for_P(.), P) -> (scanleft-to-states-declaration-for_P(.), P, left)$
[E~E{[0P>0][_H<y]<}>P{[0E>0][_H<n]}&0^] (scanleft-to-states-declaration-for_P(.), }) -> (scanleft-to-states-declaration-for_P(.), }, left)$
[E~E{[0P>0][_H<y<]>}P{[0E>0][_H<n]}&0^] (scanleft-to-states-declaration-for_P(.), ]) -> (scanleft-to-states-declaration-for_P(.), ], left)$
[E~E{[0P>0][_H<<y>]}P{[0E>0][_H<n]}&0^] (scanleft-to-states-declaration-for_P(.), y) -> (scanleft-to-states-declaration-for_P(.), y, left)$
[E~E{[0P>0][_H<<>y]}P{[0E>0][_H<n]}&0^] (scanleft-to-states-declaration-for_P(.), <) -> (scanleft-to-states-declaration-for_P(.), <, left)$
[E~E{[0P>0][_<H><y]}P{[0E>0][_H<n]}&0^] (scanleft-to-states-declaration-for_P(.), H) -> (scanleft-to-states-declaration-for_P(.), H, left)$
[E~E{[0P>0][<_>H<y]}P{[0E>0][_H<n]}&0^] (scanleft-to-states-declaration-for_P(.), _) -> (scanleft-to-states-declaration-for_P(.), _, left)$
[E~E{[0P>0]<[>_H<y]}P{[0E>0][_H<n]}&0^] (scanleft-to-states-declaration-for_P(.), [) -> (scanleft-to-states-declaration-for_P(.), [, left)$
[E~E{[0P>0<]>[_H<y]}P{[0E>0][_H<n]}&0^] (scanleft-to-states-declaration-for_P(.), ]) -> (scanleft-to-states-declaration-for_P(.), ], left)$
[E~E{[0P><0>][_H<y]}P{[0E>0][_H<n]}&0^] (scanleft-to-states-declaration-for_P(.), 0) -> (scanleft-to-states-declaration-for_P(.), 0, left)$
[E~E{[0P<>>0][_H<y]}P{[0E>0][_H<n]}&0^] (scanleft-to-states-declaration-for_P(.), >) -> (scanleft-to-states-declaration-for_P(.), >, left)$
[E~E{[0<P>>0][_H<y]}P{[0E>0][_H<n]}&0^] (scanleft-to-states-declaration-for_P(.), P) -> (scanleft-to-states-declaration-for_P(.), P, left)$
[E~E{[<0>P>0][_H<y]}P{[0E>0][_H<n]}&0^] (scanleft-to-states-declaration-for_P(.), 0) -> (scanleft-to-states-declaration-for_P(.), 0, left)$
[E~E{<[>0P>0][_H<y]}P{[0E>0][_H<n]}&0^] (scanleft-to-states-declaration-for_P(.), [) -> (scanleft-to-states-declaration-for_P(.), [, left)$
[E~E<{>[0P>0][_H<y]}P{[0E>0][_H<n]}&0^] (scanleft-to-states-declaration-for_P(.), {) -> (scanleft-to-states-declaration-for_P(.), {, left)$
[E~<E>{[0P>0][_H<y]}P{[0E>0][_H<n]}&0^] (scanleft-to-states-declaration-for_P(.), E) -> (scanleft-to-states-declaration-for_P(.), E, left)$
[E<~>E{[0P>0][_H<y]}P{[0E>0][_H<n]}&0^] (scanleft-to-states-declaration-for_P(.), ~) -> (find-state_P(.), ~, right)$
[E~<E>{[0P>0][_H<y]}P{[0E>0][_H<n]}&0^] (find-state_P(.), E) -> (scanright-to-next-state-definition_P(.), E, right)$
[E~E<{>[0P>0][_H<y]}P{[0E>0][_H<n]}&0^] (scanright-to-next-state-definition_P(.), {) -> (scanright-to-next-state-definition_P(.), {, right)$
[E~E{<[>0P>0][_H<y]}P{[0E>0][_H<n]}&0^] (scanright-to-next-state-definition_P(.), [) -> (scanright-to-next-state-definition_P(.), [, right)$
[E~E{[<0>P>0][_H<y]}P{[0E>0][_H<n]}&0^] (scanright-to-next-state-definition_P(.), 0) -> (scanright-to-next-state-definition_P(.), 0, right)$
[E~E{[0<P>>0][_H<y]}P{[0E>0][_H<n]}&0^] (scanright-to-next-state-definition_P(.), P) -> (scanright-to-next-state-definition_P(.), P, right)$
[E~E{[0P<>>0][_H<y]}P{[0E>0][_H<n]}&0^] (scanright-to-next-state-definition_P(.), >) -> (scanright-to-next-state-definition_P(.), >, right)$
[E~E{[0P><0>][_H<y]}P{[0E>0][_H<n]}&0^] (scanright-to-next-state-definition_P(.), 0) -> (scanright-to-next-state-definition_P(.), 0, right)$
[E~E{[0P>0<]>[_H<y]}P{[0E>0][_H<n]}&0^] (scanright-to-next-state-definition_P(.), ]) -> (scanright-to-next-state-definition_P(.), ], right)$
[E~E{[0P>0]<[>_H<y]}P{[0E>0][_H<n]}&0^] (scanright-to-next-state-definition_P(.), [) -> (scanright-to-next-state-definition_P(.), [, right)$
[E~E{[0P>0][<_>H<y]}P{[0E>0][_H<n]}&0^] (scanright-to-next-state-definition_P(.), _) -> (scanright-to-next-state-definition_P(.), _, right)$
[E~E{[0P>0][_<H><y]}P{[0E>0][_H<n]}&0^] (scanright-to-next-state-definition_P(.), H) -> (scanright-to-next-state-definition_P(.), H, right)$
[E~E{[0P>0][_H<<>y]}P{[0E>0][_H<n]}&0^] (scanright-to-next-state-definition_P(.), <) -> (scanright-to-next-state-definition_P(.), <, right)$
[E~E{[0P>0][_H<<y>]}P{[0E>0][_H<n]}&0^] (scanright-to-next-state-definition_P(.), y) -> (scanright-to-next-state-definition_P(.), y, right)$
[E~E{[0P>0][_H<y<]>}P{[0E>0][_H<n]}&0^] (scanright-to-next-state-definition_P(.), ]) -> (scanright-to-next-state-definition_P(.), ], right)$
[E~E{[0P>0][_H<y]<}>P{[0E>0][_H<n]}&0^] (scanright-to-next-state-definition_P(.), }) -> (find-state_P(.), }, right)$
[E~E{[0P>0][_H<y]}<P>{[0E>0][_H<n]}&0^] (find-state_P(.), P) -> (find-state-transition-for_P(.), P, right)$
[E~E{[0P>0][_H<y]}P<{>[0E>0][_H<n]}&0^] (find-state-transition-for_P(.), {) -> (find-state-transition-for_P(.), {, right)$
[E~E{[0P>0][_H<y]}P{<[>0E>0][_H<n]}&0^] (find-state-transition-for_P(.), [) -> (find-state-transition-for_P(.), [, right)$
[E~E{[0P>0][_H<y]}P{[<0>E>0][_H<n]}&0^] (find-state-transition-for_P(.), 0) -> (scanright-to-next-state-transition_P(.), 0, right)$
[E~E{[0P>0][_H<y]}P{[0<E>>0][_H<n]}&0^] (scanright-to-next-state-transition_P(.), E) -> (scanright-to-next-state-transition_P(.), E, right)$
[E~E{[0P>0][_H<y]}P{[0E<>>0][_H<n]}&0^] (scanright-to-next-state-transition_P(.), >) -> (scanright-to-next-state-transition_P(.), >, right)$
[E~E{[0P>0][_H<y]}P{[0E><0>][_H<n]}&0^] (scanright-to-next-state-transition_P(.), 0) -> (scanright-to-next-state-transition_P(.), 0, right)$
[E~E{[0P>0][_H<y]}P{[0E>0<]>[_H<n]}&0^] (scanright-to-next-state-transition_P(.), ]) -> (find-state-transition-for_P(.), ], right)$
[E~E{[0P>0][_H<y]}P{[0E>0]<[>_H<n]}&0^] (find-state-transition-for_P(.), [) -> (find-state-transition-for_P(.), [, right)$
[E~E{[0P>0][_H<y]}P{[0E>0][<_>H<n]}&0^] (find-state-transition-for_P(.), _) -> (retrieve-transition-to_state, _, right)$
[E~E{[0P>0][_H<y]}P{[0E>0][_<H><n]}&0^] (retrieve-transition-to_state, H) -> (retrieve-transition-H_action, H, right)$
[E~E{[0P>0][_H<y]}P{[0E>0][_H<<>n]}&0^] (retrieve-transition-H_action, <) -> (retrieve-transition-H_<_write, <, right)$
[E~E{[0P>0][_H<y]}P{[0E>0][_H<<n>]}&0^] (retrieve-transition-H_<_write, n) -> (execute-transition-H_<_n, n, right)$
[E~E{[0P>0][_H<y]}P{[0E>0][_H<n<]>}&0^] (execute-transition-H_<_n, ]) -> (execute-transition-H_<_n, ], right)$
[E~E{[0P>0][_H<y]}P{[0E>0][_H<n]<}>&0^] (execute-transition-H_<_n, }) -> (execute-transition-H_<_n, }, right)$
[E~E{[0P>0][_H<y]}P{[0E>0][_H<n]}<&>0^] (execute-transition-H_<_n, &) -> (execute-transition-H_<_n, &, right)$
[E~E{[0P>0][_H<y]}P{[0E>0][_H<n]}&<0>^] (execute-transition-H_<_n, 0) -> (execute-transition-H_<_n, 0, right)$
[E~E{[0P>0][_H<y]}P{[0E>0][_H<n]}&0<^>] (execute-transition-H_<_n, ^) -> (HALT, n, left)$
[E~E{[0P>0][_H<y]}P{[0E>0][_H<n]}&<0>n] Final state reached !$
Interpreter closing...$'
}

@test "'00' does match" {
    run bash -c './_build/default/bin/turing run our-machines/02n_utm.json "E~E{[0P>0][_H<y]}P{[0E>0][_H<n]}&00" | cat -e'
    assert_output 'Interpreter starting...$
[<E>~E{[0P>0][_H<y]}P{[0E>0][_H<n]}&00] (retrieve_initial_state, E) -> (go-to-input-start-for_E, E, right)$
[E<~>E{[0P>0][_H<y]}P{[0E>0][_H<n]}&00] (go-to-input-start-for_E, ~) -> (go-to-input-start-for_E, ~, right)$
[E~<E>{[0P>0][_H<y]}P{[0E>0][_H<n]}&00] (go-to-input-start-for_E, E) -> (go-to-input-start-for_E, E, right)$
[E~E<{>[0P>0][_H<y]}P{[0E>0][_H<n]}&00] (go-to-input-start-for_E, {) -> (go-to-input-start-for_E, {, right)$
[E~E{<[>0P>0][_H<y]}P{[0E>0][_H<n]}&00] (go-to-input-start-for_E, [) -> (go-to-input-start-for_E, [, right)$
[E~E{[<0>P>0][_H<y]}P{[0E>0][_H<n]}&00] (go-to-input-start-for_E, 0) -> (go-to-input-start-for_E, 0, right)$
[E~E{[0<P>>0][_H<y]}P{[0E>0][_H<n]}&00] (go-to-input-start-for_E, P) -> (go-to-input-start-for_E, P, right)$
[E~E{[0P<>>0][_H<y]}P{[0E>0][_H<n]}&00] (go-to-input-start-for_E, >) -> (go-to-input-start-for_E, >, right)$
[E~E{[0P><0>][_H<y]}P{[0E>0][_H<n]}&00] (go-to-input-start-for_E, 0) -> (go-to-input-start-for_E, 0, right)$
[E~E{[0P>0<]>[_H<y]}P{[0E>0][_H<n]}&00] (go-to-input-start-for_E, ]) -> (go-to-input-start-for_E, ], right)$
[E~E{[0P>0]<[>_H<y]}P{[0E>0][_H<n]}&00] (go-to-input-start-for_E, [) -> (go-to-input-start-for_E, [, right)$
[E~E{[0P>0][<_>H<y]}P{[0E>0][_H<n]}&00] (go-to-input-start-for_E, _) -> (go-to-input-start-for_E, _, right)$
[E~E{[0P>0][_<H><y]}P{[0E>0][_H<n]}&00] (go-to-input-start-for_E, H) -> (go-to-input-start-for_E, H, right)$
[E~E{[0P>0][_H<<>y]}P{[0E>0][_H<n]}&00] (go-to-input-start-for_E, <) -> (go-to-input-start-for_E, <, right)$
[E~E{[0P>0][_H<<y>]}P{[0E>0][_H<n]}&00] (go-to-input-start-for_E, y) -> (go-to-input-start-for_E, y, right)$
[E~E{[0P>0][_H<y<]>}P{[0E>0][_H<n]}&00] (go-to-input-start-for_E, ]) -> (go-to-input-start-for_E, ], right)$
[E~E{[0P>0][_H<y]<}>P{[0E>0][_H<n]}&00] (go-to-input-start-for_E, }) -> (go-to-input-start-for_E, }, right)$
[E~E{[0P>0][_H<y]}<P>{[0E>0][_H<n]}&00] (go-to-input-start-for_E, P) -> (go-to-input-start-for_E, P, right)$
[E~E{[0P>0][_H<y]}P<{>[0E>0][_H<n]}&00] (go-to-input-start-for_E, {) -> (go-to-input-start-for_E, {, right)$
[E~E{[0P>0][_H<y]}P{<[>0E>0][_H<n]}&00] (go-to-input-start-for_E, [) -> (go-to-input-start-for_E, [, right)$
[E~E{[0P>0][_H<y]}P{[<0>E>0][_H<n]}&00] (go-to-input-start-for_E, 0) -> (go-to-input-start-for_E, 0, right)$
[E~E{[0P>0][_H<y]}P{[0<E>>0][_H<n]}&00] (go-to-input-start-for_E, E) -> (go-to-input-start-for_E, E, right)$
[E~E{[0P>0][_H<y]}P{[0E<>>0][_H<n]}&00] (go-to-input-start-for_E, >) -> (go-to-input-start-for_E, >, right)$
[E~E{[0P>0][_H<y]}P{[0E><0>][_H<n]}&00] (go-to-input-start-for_E, 0) -> (go-to-input-start-for_E, 0, right)$
[E~E{[0P>0][_H<y]}P{[0E>0<]>[_H<n]}&00] (go-to-input-start-for_E, ]) -> (go-to-input-start-for_E, ], right)$
[E~E{[0P>0][_H<y]}P{[0E>0]<[>_H<n]}&00] (go-to-input-start-for_E, [) -> (go-to-input-start-for_E, [, right)$
[E~E{[0P>0][_H<y]}P{[0E>0][<_>H<n]}&00] (go-to-input-start-for_E, _) -> (go-to-input-start-for_E, _, right)$
[E~E{[0P>0][_H<y]}P{[0E>0][_<H><n]}&00] (go-to-input-start-for_E, H) -> (go-to-input-start-for_E, H, right)$
[E~E{[0P>0][_H<y]}P{[0E>0][_H<<>n]}&00] (go-to-input-start-for_E, <) -> (go-to-input-start-for_E, <, right)$
[E~E{[0P>0][_H<y]}P{[0E>0][_H<<n>]}&00] (go-to-input-start-for_E, n) -> (go-to-input-start-for_E, n, right)$
[E~E{[0P>0][_H<y]}P{[0E>0][_H<n<]>}&00] (go-to-input-start-for_E, ]) -> (go-to-input-start-for_E, ], right)$
[E~E{[0P>0][_H<y]}P{[0E>0][_H<n]<}>&00] (go-to-input-start-for_E, }) -> (go-to-input-start-for_E, }, right)$
[E~E{[0P>0][_H<y]}P{[0E>0][_H<n]}<&>00] (go-to-input-start-for_E, &) -> (read-tape-for_E, &, right)$
[E~E{[0P>0][_H<y]}P{[0E>0][_H<n]}&<0>0] (read-tape-for_E, 0) -> (scanleft-to-states-declaration-for_E(0), ^, left)$
[E~E{[0P>0][_H<y]}P{[0E>0][_H<n]}<&>^0] (scanleft-to-states-declaration-for_E(0), &) -> (scanleft-to-states-declaration-for_E(0), &, left)$
[E~E{[0P>0][_H<y]}P{[0E>0][_H<n]<}>&^0] (scanleft-to-states-declaration-for_E(0), }) -> (scanleft-to-states-declaration-for_E(0), }, left)$
[E~E{[0P>0][_H<y]}P{[0E>0][_H<n<]>}&^0] (scanleft-to-states-declaration-for_E(0), ]) -> (scanleft-to-states-declaration-for_E(0), ], left)$
[E~E{[0P>0][_H<y]}P{[0E>0][_H<<n>]}&^0] (scanleft-to-states-declaration-for_E(0), n) -> (scanleft-to-states-declaration-for_E(0), n, left)$
[E~E{[0P>0][_H<y]}P{[0E>0][_H<<>n]}&^0] (scanleft-to-states-declaration-for_E(0), <) -> (scanleft-to-states-declaration-for_E(0), <, left)$
[E~E{[0P>0][_H<y]}P{[0E>0][_<H><n]}&^0] (scanleft-to-states-declaration-for_E(0), H) -> (scanleft-to-states-declaration-for_E(0), H, left)$
[E~E{[0P>0][_H<y]}P{[0E>0][<_>H<n]}&^0] (scanleft-to-states-declaration-for_E(0), _) -> (scanleft-to-states-declaration-for_E(0), _, left)$
[E~E{[0P>0][_H<y]}P{[0E>0]<[>_H<n]}&^0] (scanleft-to-states-declaration-for_E(0), [) -> (scanleft-to-states-declaration-for_E(0), [, left)$
[E~E{[0P>0][_H<y]}P{[0E>0<]>[_H<n]}&^0] (scanleft-to-states-declaration-for_E(0), ]) -> (scanleft-to-states-declaration-for_E(0), ], left)$
[E~E{[0P>0][_H<y]}P{[0E><0>][_H<n]}&^0] (scanleft-to-states-declaration-for_E(0), 0) -> (scanleft-to-states-declaration-for_E(0), 0, left)$
[E~E{[0P>0][_H<y]}P{[0E<>>0][_H<n]}&^0] (scanleft-to-states-declaration-for_E(0), >) -> (scanleft-to-states-declaration-for_E(0), >, left)$
[E~E{[0P>0][_H<y]}P{[0<E>>0][_H<n]}&^0] (scanleft-to-states-declaration-for_E(0), E) -> (scanleft-to-states-declaration-for_E(0), E, left)$
[E~E{[0P>0][_H<y]}P{[<0>E>0][_H<n]}&^0] (scanleft-to-states-declaration-for_E(0), 0) -> (scanleft-to-states-declaration-for_E(0), 0, left)$
[E~E{[0P>0][_H<y]}P{<[>0E>0][_H<n]}&^0] (scanleft-to-states-declaration-for_E(0), [) -> (scanleft-to-states-declaration-for_E(0), [, left)$
[E~E{[0P>0][_H<y]}P<{>[0E>0][_H<n]}&^0] (scanleft-to-states-declaration-for_E(0), {) -> (scanleft-to-states-declaration-for_E(0), {, left)$
[E~E{[0P>0][_H<y]}<P>{[0E>0][_H<n]}&^0] (scanleft-to-states-declaration-for_E(0), P) -> (scanleft-to-states-declaration-for_E(0), P, left)$
[E~E{[0P>0][_H<y]<}>P{[0E>0][_H<n]}&^0] (scanleft-to-states-declaration-for_E(0), }) -> (scanleft-to-states-declaration-for_E(0), }, left)$
[E~E{[0P>0][_H<y<]>}P{[0E>0][_H<n]}&^0] (scanleft-to-states-declaration-for_E(0), ]) -> (scanleft-to-states-declaration-for_E(0), ], left)$
[E~E{[0P>0][_H<<y>]}P{[0E>0][_H<n]}&^0] (scanleft-to-states-declaration-for_E(0), y) -> (scanleft-to-states-declaration-for_E(0), y, left)$
[E~E{[0P>0][_H<<>y]}P{[0E>0][_H<n]}&^0] (scanleft-to-states-declaration-for_E(0), <) -> (scanleft-to-states-declaration-for_E(0), <, left)$
[E~E{[0P>0][_<H><y]}P{[0E>0][_H<n]}&^0] (scanleft-to-states-declaration-for_E(0), H) -> (scanleft-to-states-declaration-for_E(0), H, left)$
[E~E{[0P>0][<_>H<y]}P{[0E>0][_H<n]}&^0] (scanleft-to-states-declaration-for_E(0), _) -> (scanleft-to-states-declaration-for_E(0), _, left)$
[E~E{[0P>0]<[>_H<y]}P{[0E>0][_H<n]}&^0] (scanleft-to-states-declaration-for_E(0), [) -> (scanleft-to-states-declaration-for_E(0), [, left)$
[E~E{[0P>0<]>[_H<y]}P{[0E>0][_H<n]}&^0] (scanleft-to-states-declaration-for_E(0), ]) -> (scanleft-to-states-declaration-for_E(0), ], left)$
[E~E{[0P><0>][_H<y]}P{[0E>0][_H<n]}&^0] (scanleft-to-states-declaration-for_E(0), 0) -> (scanleft-to-states-declaration-for_E(0), 0, left)$
[E~E{[0P<>>0][_H<y]}P{[0E>0][_H<n]}&^0] (scanleft-to-states-declaration-for_E(0), >) -> (scanleft-to-states-declaration-for_E(0), >, left)$
[E~E{[0<P>>0][_H<y]}P{[0E>0][_H<n]}&^0] (scanleft-to-states-declaration-for_E(0), P) -> (scanleft-to-states-declaration-for_E(0), P, left)$
[E~E{[<0>P>0][_H<y]}P{[0E>0][_H<n]}&^0] (scanleft-to-states-declaration-for_E(0), 0) -> (scanleft-to-states-declaration-for_E(0), 0, left)$
[E~E{<[>0P>0][_H<y]}P{[0E>0][_H<n]}&^0] (scanleft-to-states-declaration-for_E(0), [) -> (scanleft-to-states-declaration-for_E(0), [, left)$
[E~E<{>[0P>0][_H<y]}P{[0E>0][_H<n]}&^0] (scanleft-to-states-declaration-for_E(0), {) -> (scanleft-to-states-declaration-for_E(0), {, left)$
[E~<E>{[0P>0][_H<y]}P{[0E>0][_H<n]}&^0] (scanleft-to-states-declaration-for_E(0), E) -> (scanleft-to-states-declaration-for_E(0), E, left)$
[E<~>E{[0P>0][_H<y]}P{[0E>0][_H<n]}&^0] (scanleft-to-states-declaration-for_E(0), ~) -> (find-state_E(0), ~, right)$
[E~<E>{[0P>0][_H<y]}P{[0E>0][_H<n]}&^0] (find-state_E(0), E) -> (find-state-transition-for_E(0), E, right)$
[E~E<{>[0P>0][_H<y]}P{[0E>0][_H<n]}&^0] (find-state-transition-for_E(0), {) -> (find-state-transition-for_E(0), {, right)$
[E~E{<[>0P>0][_H<y]}P{[0E>0][_H<n]}&^0] (find-state-transition-for_E(0), [) -> (find-state-transition-for_E(0), [, right)$
[E~E{[<0>P>0][_H<y]}P{[0E>0][_H<n]}&^0] (find-state-transition-for_E(0), 0) -> (retrieve-transition-to_state, 0, right)$
[E~E{[0<P>>0][_H<y]}P{[0E>0][_H<n]}&^0] (retrieve-transition-to_state, P) -> (retrieve-transition-P_action, P, right)$
[E~E{[0P<>>0][_H<y]}P{[0E>0][_H<n]}&^0] (retrieve-transition-P_action, >) -> (retrieve-transition-P_>_write, >, right)$
[E~E{[0P><0>][_H<y]}P{[0E>0][_H<n]}&^0] (retrieve-transition-P_>_write, 0) -> (execute-transition-P_>_0, 0, right)$
[E~E{[0P>0<]>[_H<y]}P{[0E>0][_H<n]}&^0] (execute-transition-P_>_0, ]) -> (execute-transition-P_>_0, ], right)$
[E~E{[0P>0]<[>_H<y]}P{[0E>0][_H<n]}&^0] (execute-transition-P_>_0, [) -> (execute-transition-P_>_0, [, right)$
[E~E{[0P>0][<_>H<y]}P{[0E>0][_H<n]}&^0] (execute-transition-P_>_0, _) -> (execute-transition-P_>_0, _, right)$
[E~E{[0P>0][_<H><y]}P{[0E>0][_H<n]}&^0] (execute-transition-P_>_0, H) -> (execute-transition-P_>_0, H, right)$
[E~E{[0P>0][_H<<>y]}P{[0E>0][_H<n]}&^0] (execute-transition-P_>_0, <) -> (execute-transition-P_>_0, <, right)$
[E~E{[0P>0][_H<<y>]}P{[0E>0][_H<n]}&^0] (execute-transition-P_>_0, y) -> (execute-transition-P_>_0, y, right)$
[E~E{[0P>0][_H<y<]>}P{[0E>0][_H<n]}&^0] (execute-transition-P_>_0, ]) -> (execute-transition-P_>_0, ], right)$
[E~E{[0P>0][_H<y]<}>P{[0E>0][_H<n]}&^0] (execute-transition-P_>_0, }) -> (execute-transition-P_>_0, }, right)$
[E~E{[0P>0][_H<y]}<P>{[0E>0][_H<n]}&^0] (execute-transition-P_>_0, P) -> (execute-transition-P_>_0, P, right)$
[E~E{[0P>0][_H<y]}P<{>[0E>0][_H<n]}&^0] (execute-transition-P_>_0, {) -> (execute-transition-P_>_0, {, right)$
[E~E{[0P>0][_H<y]}P{<[>0E>0][_H<n]}&^0] (execute-transition-P_>_0, [) -> (execute-transition-P_>_0, [, right)$
[E~E{[0P>0][_H<y]}P{[<0>E>0][_H<n]}&^0] (execute-transition-P_>_0, 0) -> (execute-transition-P_>_0, 0, right)$
[E~E{[0P>0][_H<y]}P{[0<E>>0][_H<n]}&^0] (execute-transition-P_>_0, E) -> (execute-transition-P_>_0, E, right)$
[E~E{[0P>0][_H<y]}P{[0E<>>0][_H<n]}&^0] (execute-transition-P_>_0, >) -> (execute-transition-P_>_0, >, right)$
[E~E{[0P>0][_H<y]}P{[0E><0>][_H<n]}&^0] (execute-transition-P_>_0, 0) -> (execute-transition-P_>_0, 0, right)$
[E~E{[0P>0][_H<y]}P{[0E>0<]>[_H<n]}&^0] (execute-transition-P_>_0, ]) -> (execute-transition-P_>_0, ], right)$
[E~E{[0P>0][_H<y]}P{[0E>0]<[>_H<n]}&^0] (execute-transition-P_>_0, [) -> (execute-transition-P_>_0, [, right)$
[E~E{[0P>0][_H<y]}P{[0E>0][<_>H<n]}&^0] (execute-transition-P_>_0, _) -> (execute-transition-P_>_0, _, right)$
[E~E{[0P>0][_H<y]}P{[0E>0][_<H><n]}&^0] (execute-transition-P_>_0, H) -> (execute-transition-P_>_0, H, right)$
[E~E{[0P>0][_H<y]}P{[0E>0][_H<<>n]}&^0] (execute-transition-P_>_0, <) -> (execute-transition-P_>_0, <, right)$
[E~E{[0P>0][_H<y]}P{[0E>0][_H<<n>]}&^0] (execute-transition-P_>_0, n) -> (execute-transition-P_>_0, n, right)$
[E~E{[0P>0][_H<y]}P{[0E>0][_H<n<]>}&^0] (execute-transition-P_>_0, ]) -> (execute-transition-P_>_0, ], right)$
[E~E{[0P>0][_H<y]}P{[0E>0][_H<n]<}>&^0] (execute-transition-P_>_0, }) -> (execute-transition-P_>_0, }, right)$
[E~E{[0P>0][_H<y]}P{[0E>0][_H<n]}<&>^0] (execute-transition-P_>_0, &) -> (execute-transition-P_>_0, &, right)$
[E~E{[0P>0][_H<y]}P{[0E>0][_H<n]}&<^>0] (execute-transition-P_>_0, ^) -> (read-tape-for_P, 0, right)$
[E~E{[0P>0][_H<y]}P{[0E>0][_H<n]}&0<0>] (read-tape-for_P, 0) -> (scanleft-to-states-declaration-for_P(0), ^, left)$
[E~E{[0P>0][_H<y]}P{[0E>0][_H<n]}&<0>^] (scanleft-to-states-declaration-for_P(0), 0) -> (scanleft-to-states-declaration-for_P(0), 0, left)$
[E~E{[0P>0][_H<y]}P{[0E>0][_H<n]}<&>0^] (scanleft-to-states-declaration-for_P(0), &) -> (scanleft-to-states-declaration-for_P(0), &, left)$
[E~E{[0P>0][_H<y]}P{[0E>0][_H<n]<}>&0^] (scanleft-to-states-declaration-for_P(0), }) -> (scanleft-to-states-declaration-for_P(0), }, left)$
[E~E{[0P>0][_H<y]}P{[0E>0][_H<n<]>}&0^] (scanleft-to-states-declaration-for_P(0), ]) -> (scanleft-to-states-declaration-for_P(0), ], left)$
[E~E{[0P>0][_H<y]}P{[0E>0][_H<<n>]}&0^] (scanleft-to-states-declaration-for_P(0), n) -> (scanleft-to-states-declaration-for_P(0), n, left)$
[E~E{[0P>0][_H<y]}P{[0E>0][_H<<>n]}&0^] (scanleft-to-states-declaration-for_P(0), <) -> (scanleft-to-states-declaration-for_P(0), <, left)$
[E~E{[0P>0][_H<y]}P{[0E>0][_<H><n]}&0^] (scanleft-to-states-declaration-for_P(0), H) -> (scanleft-to-states-declaration-for_P(0), H, left)$
[E~E{[0P>0][_H<y]}P{[0E>0][<_>H<n]}&0^] (scanleft-to-states-declaration-for_P(0), _) -> (scanleft-to-states-declaration-for_P(0), _, left)$
[E~E{[0P>0][_H<y]}P{[0E>0]<[>_H<n]}&0^] (scanleft-to-states-declaration-for_P(0), [) -> (scanleft-to-states-declaration-for_P(0), [, left)$
[E~E{[0P>0][_H<y]}P{[0E>0<]>[_H<n]}&0^] (scanleft-to-states-declaration-for_P(0), ]) -> (scanleft-to-states-declaration-for_P(0), ], left)$
[E~E{[0P>0][_H<y]}P{[0E><0>][_H<n]}&0^] (scanleft-to-states-declaration-for_P(0), 0) -> (scanleft-to-states-declaration-for_P(0), 0, left)$
[E~E{[0P>0][_H<y]}P{[0E<>>0][_H<n]}&0^] (scanleft-to-states-declaration-for_P(0), >) -> (scanleft-to-states-declaration-for_P(0), >, left)$
[E~E{[0P>0][_H<y]}P{[0<E>>0][_H<n]}&0^] (scanleft-to-states-declaration-for_P(0), E) -> (scanleft-to-states-declaration-for_P(0), E, left)$
[E~E{[0P>0][_H<y]}P{[<0>E>0][_H<n]}&0^] (scanleft-to-states-declaration-for_P(0), 0) -> (scanleft-to-states-declaration-for_P(0), 0, left)$
[E~E{[0P>0][_H<y]}P{<[>0E>0][_H<n]}&0^] (scanleft-to-states-declaration-for_P(0), [) -> (scanleft-to-states-declaration-for_P(0), [, left)$
[E~E{[0P>0][_H<y]}P<{>[0E>0][_H<n]}&0^] (scanleft-to-states-declaration-for_P(0), {) -> (scanleft-to-states-declaration-for_P(0), {, left)$
[E~E{[0P>0][_H<y]}<P>{[0E>0][_H<n]}&0^] (scanleft-to-states-declaration-for_P(0), P) -> (scanleft-to-states-declaration-for_P(0), P, left)$
[E~E{[0P>0][_H<y]<}>P{[0E>0][_H<n]}&0^] (scanleft-to-states-declaration-for_P(0), }) -> (scanleft-to-states-declaration-for_P(0), }, left)$
[E~E{[0P>0][_H<y<]>}P{[0E>0][_H<n]}&0^] (scanleft-to-states-declaration-for_P(0), ]) -> (scanleft-to-states-declaration-for_P(0), ], left)$
[E~E{[0P>0][_H<<y>]}P{[0E>0][_H<n]}&0^] (scanleft-to-states-declaration-for_P(0), y) -> (scanleft-to-states-declaration-for_P(0), y, left)$
[E~E{[0P>0][_H<<>y]}P{[0E>0][_H<n]}&0^] (scanleft-to-states-declaration-for_P(0), <) -> (scanleft-to-states-declaration-for_P(0), <, left)$
[E~E{[0P>0][_<H><y]}P{[0E>0][_H<n]}&0^] (scanleft-to-states-declaration-for_P(0), H) -> (scanleft-to-states-declaration-for_P(0), H, left)$
[E~E{[0P>0][<_>H<y]}P{[0E>0][_H<n]}&0^] (scanleft-to-states-declaration-for_P(0), _) -> (scanleft-to-states-declaration-for_P(0), _, left)$
[E~E{[0P>0]<[>_H<y]}P{[0E>0][_H<n]}&0^] (scanleft-to-states-declaration-for_P(0), [) -> (scanleft-to-states-declaration-for_P(0), [, left)$
[E~E{[0P>0<]>[_H<y]}P{[0E>0][_H<n]}&0^] (scanleft-to-states-declaration-for_P(0), ]) -> (scanleft-to-states-declaration-for_P(0), ], left)$
[E~E{[0P><0>][_H<y]}P{[0E>0][_H<n]}&0^] (scanleft-to-states-declaration-for_P(0), 0) -> (scanleft-to-states-declaration-for_P(0), 0, left)$
[E~E{[0P<>>0][_H<y]}P{[0E>0][_H<n]}&0^] (scanleft-to-states-declaration-for_P(0), >) -> (scanleft-to-states-declaration-for_P(0), >, left)$
[E~E{[0<P>>0][_H<y]}P{[0E>0][_H<n]}&0^] (scanleft-to-states-declaration-for_P(0), P) -> (scanleft-to-states-declaration-for_P(0), P, left)$
[E~E{[<0>P>0][_H<y]}P{[0E>0][_H<n]}&0^] (scanleft-to-states-declaration-for_P(0), 0) -> (scanleft-to-states-declaration-for_P(0), 0, left)$
[E~E{<[>0P>0][_H<y]}P{[0E>0][_H<n]}&0^] (scanleft-to-states-declaration-for_P(0), [) -> (scanleft-to-states-declaration-for_P(0), [, left)$
[E~E<{>[0P>0][_H<y]}P{[0E>0][_H<n]}&0^] (scanleft-to-states-declaration-for_P(0), {) -> (scanleft-to-states-declaration-for_P(0), {, left)$
[E~<E>{[0P>0][_H<y]}P{[0E>0][_H<n]}&0^] (scanleft-to-states-declaration-for_P(0), E) -> (scanleft-to-states-declaration-for_P(0), E, left)$
[E<~>E{[0P>0][_H<y]}P{[0E>0][_H<n]}&0^] (scanleft-to-states-declaration-for_P(0), ~) -> (find-state_P(0), ~, right)$
[E~<E>{[0P>0][_H<y]}P{[0E>0][_H<n]}&0^] (find-state_P(0), E) -> (scanright-to-next-state-definition_P(0), E, right)$
[E~E<{>[0P>0][_H<y]}P{[0E>0][_H<n]}&0^] (scanright-to-next-state-definition_P(0), {) -> (scanright-to-next-state-definition_P(0), {, right)$
[E~E{<[>0P>0][_H<y]}P{[0E>0][_H<n]}&0^] (scanright-to-next-state-definition_P(0), [) -> (scanright-to-next-state-definition_P(0), [, right)$
[E~E{[<0>P>0][_H<y]}P{[0E>0][_H<n]}&0^] (scanright-to-next-state-definition_P(0), 0) -> (scanright-to-next-state-definition_P(0), 0, right)$
[E~E{[0<P>>0][_H<y]}P{[0E>0][_H<n]}&0^] (scanright-to-next-state-definition_P(0), P) -> (scanright-to-next-state-definition_P(0), P, right)$
[E~E{[0P<>>0][_H<y]}P{[0E>0][_H<n]}&0^] (scanright-to-next-state-definition_P(0), >) -> (scanright-to-next-state-definition_P(0), >, right)$
[E~E{[0P><0>][_H<y]}P{[0E>0][_H<n]}&0^] (scanright-to-next-state-definition_P(0), 0) -> (scanright-to-next-state-definition_P(0), 0, right)$
[E~E{[0P>0<]>[_H<y]}P{[0E>0][_H<n]}&0^] (scanright-to-next-state-definition_P(0), ]) -> (scanright-to-next-state-definition_P(0), ], right)$
[E~E{[0P>0]<[>_H<y]}P{[0E>0][_H<n]}&0^] (scanright-to-next-state-definition_P(0), [) -> (scanright-to-next-state-definition_P(0), [, right)$
[E~E{[0P>0][<_>H<y]}P{[0E>0][_H<n]}&0^] (scanright-to-next-state-definition_P(0), _) -> (scanright-to-next-state-definition_P(0), _, right)$
[E~E{[0P>0][_<H><y]}P{[0E>0][_H<n]}&0^] (scanright-to-next-state-definition_P(0), H) -> (scanright-to-next-state-definition_P(0), H, right)$
[E~E{[0P>0][_H<<>y]}P{[0E>0][_H<n]}&0^] (scanright-to-next-state-definition_P(0), <) -> (scanright-to-next-state-definition_P(0), <, right)$
[E~E{[0P>0][_H<<y>]}P{[0E>0][_H<n]}&0^] (scanright-to-next-state-definition_P(0), y) -> (scanright-to-next-state-definition_P(0), y, right)$
[E~E{[0P>0][_H<y<]>}P{[0E>0][_H<n]}&0^] (scanright-to-next-state-definition_P(0), ]) -> (scanright-to-next-state-definition_P(0), ], right)$
[E~E{[0P>0][_H<y]<}>P{[0E>0][_H<n]}&0^] (scanright-to-next-state-definition_P(0), }) -> (find-state_P(0), }, right)$
[E~E{[0P>0][_H<y]}<P>{[0E>0][_H<n]}&0^] (find-state_P(0), P) -> (find-state-transition-for_P(0), P, right)$
[E~E{[0P>0][_H<y]}P<{>[0E>0][_H<n]}&0^] (find-state-transition-for_P(0), {) -> (find-state-transition-for_P(0), {, right)$
[E~E{[0P>0][_H<y]}P{<[>0E>0][_H<n]}&0^] (find-state-transition-for_P(0), [) -> (find-state-transition-for_P(0), [, right)$
[E~E{[0P>0][_H<y]}P{[<0>E>0][_H<n]}&0^] (find-state-transition-for_P(0), 0) -> (retrieve-transition-to_state, 0, right)$
[E~E{[0P>0][_H<y]}P{[0<E>>0][_H<n]}&0^] (retrieve-transition-to_state, E) -> (retrieve-transition-E_action, E, right)$
[E~E{[0P>0][_H<y]}P{[0E<>>0][_H<n]}&0^] (retrieve-transition-E_action, >) -> (retrieve-transition-E_>_write, >, right)$
[E~E{[0P>0][_H<y]}P{[0E><0>][_H<n]}&0^] (retrieve-transition-E_>_write, 0) -> (execute-transition-E_>_0, 0, right)$
[E~E{[0P>0][_H<y]}P{[0E>0<]>[_H<n]}&0^] (execute-transition-E_>_0, ]) -> (execute-transition-E_>_0, ], right)$
[E~E{[0P>0][_H<y]}P{[0E>0]<[>_H<n]}&0^] (execute-transition-E_>_0, [) -> (execute-transition-E_>_0, [, right)$
[E~E{[0P>0][_H<y]}P{[0E>0][<_>H<n]}&0^] (execute-transition-E_>_0, _) -> (execute-transition-E_>_0, _, right)$
[E~E{[0P>0][_H<y]}P{[0E>0][_<H><n]}&0^] (execute-transition-E_>_0, H) -> (execute-transition-E_>_0, H, right)$
[E~E{[0P>0][_H<y]}P{[0E>0][_H<<>n]}&0^] (execute-transition-E_>_0, <) -> (execute-transition-E_>_0, <, right)$
[E~E{[0P>0][_H<y]}P{[0E>0][_H<<n>]}&0^] (execute-transition-E_>_0, n) -> (execute-transition-E_>_0, n, right)$
[E~E{[0P>0][_H<y]}P{[0E>0][_H<n<]>}&0^] (execute-transition-E_>_0, ]) -> (execute-transition-E_>_0, ], right)$
[E~E{[0P>0][_H<y]}P{[0E>0][_H<n]<}>&0^] (execute-transition-E_>_0, }) -> (execute-transition-E_>_0, }, right)$
[E~E{[0P>0][_H<y]}P{[0E>0][_H<n]}<&>0^] (execute-transition-E_>_0, &) -> (execute-transition-E_>_0, &, right)$
[E~E{[0P>0][_H<y]}P{[0E>0][_H<n]}&<0>^] (execute-transition-E_>_0, 0) -> (execute-transition-E_>_0, 0, right)$
[E~E{[0P>0][_H<y]}P{[0E>0][_H<n]}&0<^>] (execute-transition-E_>_0, ^) -> (read-tape-for_E, 0, right)$
[E~E{[0P>0][_H<y]}P{[0E>0][_H<n]}&00<.>] (read-tape-for_E, .) -> (scanleft-to-states-declaration-for_E(.), ^, left)$
[E~E{[0P>0][_H<y]}P{[0E>0][_H<n]}&0<0>^] (scanleft-to-states-declaration-for_E(.), 0) -> (scanleft-to-states-declaration-for_E(.), 0, left)$
[E~E{[0P>0][_H<y]}P{[0E>0][_H<n]}&<0>0^] (scanleft-to-states-declaration-for_E(.), 0) -> (scanleft-to-states-declaration-for_E(.), 0, left)$
[E~E{[0P>0][_H<y]}P{[0E>0][_H<n]}<&>00^] (scanleft-to-states-declaration-for_E(.), &) -> (scanleft-to-states-declaration-for_E(.), &, left)$
[E~E{[0P>0][_H<y]}P{[0E>0][_H<n]<}>&00^] (scanleft-to-states-declaration-for_E(.), }) -> (scanleft-to-states-declaration-for_E(.), }, left)$
[E~E{[0P>0][_H<y]}P{[0E>0][_H<n<]>}&00^] (scanleft-to-states-declaration-for_E(.), ]) -> (scanleft-to-states-declaration-for_E(.), ], left)$
[E~E{[0P>0][_H<y]}P{[0E>0][_H<<n>]}&00^] (scanleft-to-states-declaration-for_E(.), n) -> (scanleft-to-states-declaration-for_E(.), n, left)$
[E~E{[0P>0][_H<y]}P{[0E>0][_H<<>n]}&00^] (scanleft-to-states-declaration-for_E(.), <) -> (scanleft-to-states-declaration-for_E(.), <, left)$
[E~E{[0P>0][_H<y]}P{[0E>0][_<H><n]}&00^] (scanleft-to-states-declaration-for_E(.), H) -> (scanleft-to-states-declaration-for_E(.), H, left)$
[E~E{[0P>0][_H<y]}P{[0E>0][<_>H<n]}&00^] (scanleft-to-states-declaration-for_E(.), _) -> (scanleft-to-states-declaration-for_E(.), _, left)$
[E~E{[0P>0][_H<y]}P{[0E>0]<[>_H<n]}&00^] (scanleft-to-states-declaration-for_E(.), [) -> (scanleft-to-states-declaration-for_E(.), [, left)$
[E~E{[0P>0][_H<y]}P{[0E>0<]>[_H<n]}&00^] (scanleft-to-states-declaration-for_E(.), ]) -> (scanleft-to-states-declaration-for_E(.), ], left)$
[E~E{[0P>0][_H<y]}P{[0E><0>][_H<n]}&00^] (scanleft-to-states-declaration-for_E(.), 0) -> (scanleft-to-states-declaration-for_E(.), 0, left)$
[E~E{[0P>0][_H<y]}P{[0E<>>0][_H<n]}&00^] (scanleft-to-states-declaration-for_E(.), >) -> (scanleft-to-states-declaration-for_E(.), >, left)$
[E~E{[0P>0][_H<y]}P{[0<E>>0][_H<n]}&00^] (scanleft-to-states-declaration-for_E(.), E) -> (scanleft-to-states-declaration-for_E(.), E, left)$
[E~E{[0P>0][_H<y]}P{[<0>E>0][_H<n]}&00^] (scanleft-to-states-declaration-for_E(.), 0) -> (scanleft-to-states-declaration-for_E(.), 0, left)$
[E~E{[0P>0][_H<y]}P{<[>0E>0][_H<n]}&00^] (scanleft-to-states-declaration-for_E(.), [) -> (scanleft-to-states-declaration-for_E(.), [, left)$
[E~E{[0P>0][_H<y]}P<{>[0E>0][_H<n]}&00^] (scanleft-to-states-declaration-for_E(.), {) -> (scanleft-to-states-declaration-for_E(.), {, left)$
[E~E{[0P>0][_H<y]}<P>{[0E>0][_H<n]}&00^] (scanleft-to-states-declaration-for_E(.), P) -> (scanleft-to-states-declaration-for_E(.), P, left)$
[E~E{[0P>0][_H<y]<}>P{[0E>0][_H<n]}&00^] (scanleft-to-states-declaration-for_E(.), }) -> (scanleft-to-states-declaration-for_E(.), }, left)$
[E~E{[0P>0][_H<y<]>}P{[0E>0][_H<n]}&00^] (scanleft-to-states-declaration-for_E(.), ]) -> (scanleft-to-states-declaration-for_E(.), ], left)$
[E~E{[0P>0][_H<<y>]}P{[0E>0][_H<n]}&00^] (scanleft-to-states-declaration-for_E(.), y) -> (scanleft-to-states-declaration-for_E(.), y, left)$
[E~E{[0P>0][_H<<>y]}P{[0E>0][_H<n]}&00^] (scanleft-to-states-declaration-for_E(.), <) -> (scanleft-to-states-declaration-for_E(.), <, left)$
[E~E{[0P>0][_<H><y]}P{[0E>0][_H<n]}&00^] (scanleft-to-states-declaration-for_E(.), H) -> (scanleft-to-states-declaration-for_E(.), H, left)$
[E~E{[0P>0][<_>H<y]}P{[0E>0][_H<n]}&00^] (scanleft-to-states-declaration-for_E(.), _) -> (scanleft-to-states-declaration-for_E(.), _, left)$
[E~E{[0P>0]<[>_H<y]}P{[0E>0][_H<n]}&00^] (scanleft-to-states-declaration-for_E(.), [) -> (scanleft-to-states-declaration-for_E(.), [, left)$
[E~E{[0P>0<]>[_H<y]}P{[0E>0][_H<n]}&00^] (scanleft-to-states-declaration-for_E(.), ]) -> (scanleft-to-states-declaration-for_E(.), ], left)$
[E~E{[0P><0>][_H<y]}P{[0E>0][_H<n]}&00^] (scanleft-to-states-declaration-for_E(.), 0) -> (scanleft-to-states-declaration-for_E(.), 0, left)$
[E~E{[0P<>>0][_H<y]}P{[0E>0][_H<n]}&00^] (scanleft-to-states-declaration-for_E(.), >) -> (scanleft-to-states-declaration-for_E(.), >, left)$
[E~E{[0<P>>0][_H<y]}P{[0E>0][_H<n]}&00^] (scanleft-to-states-declaration-for_E(.), P) -> (scanleft-to-states-declaration-for_E(.), P, left)$
[E~E{[<0>P>0][_H<y]}P{[0E>0][_H<n]}&00^] (scanleft-to-states-declaration-for_E(.), 0) -> (scanleft-to-states-declaration-for_E(.), 0, left)$
[E~E{<[>0P>0][_H<y]}P{[0E>0][_H<n]}&00^] (scanleft-to-states-declaration-for_E(.), [) -> (scanleft-to-states-declaration-for_E(.), [, left)$
[E~E<{>[0P>0][_H<y]}P{[0E>0][_H<n]}&00^] (scanleft-to-states-declaration-for_E(.), {) -> (scanleft-to-states-declaration-for_E(.), {, left)$
[E~<E>{[0P>0][_H<y]}P{[0E>0][_H<n]}&00^] (scanleft-to-states-declaration-for_E(.), E) -> (scanleft-to-states-declaration-for_E(.), E, left)$
[E<~>E{[0P>0][_H<y]}P{[0E>0][_H<n]}&00^] (scanleft-to-states-declaration-for_E(.), ~) -> (find-state_E(.), ~, right)$
[E~<E>{[0P>0][_H<y]}P{[0E>0][_H<n]}&00^] (find-state_E(.), E) -> (find-state-transition-for_E(.), E, right)$
[E~E<{>[0P>0][_H<y]}P{[0E>0][_H<n]}&00^] (find-state-transition-for_E(.), {) -> (find-state-transition-for_E(.), {, right)$
[E~E{<[>0P>0][_H<y]}P{[0E>0][_H<n]}&00^] (find-state-transition-for_E(.), [) -> (find-state-transition-for_E(.), [, right)$
[E~E{[<0>P>0][_H<y]}P{[0E>0][_H<n]}&00^] (find-state-transition-for_E(.), 0) -> (scanright-to-next-state-transition_E(.), 0, right)$
[E~E{[0<P>>0][_H<y]}P{[0E>0][_H<n]}&00^] (scanright-to-next-state-transition_E(.), P) -> (scanright-to-next-state-transition_E(.), P, right)$
[E~E{[0P<>>0][_H<y]}P{[0E>0][_H<n]}&00^] (scanright-to-next-state-transition_E(.), >) -> (scanright-to-next-state-transition_E(.), >, right)$
[E~E{[0P><0>][_H<y]}P{[0E>0][_H<n]}&00^] (scanright-to-next-state-transition_E(.), 0) -> (scanright-to-next-state-transition_E(.), 0, right)$
[E~E{[0P>0<]>[_H<y]}P{[0E>0][_H<n]}&00^] (scanright-to-next-state-transition_E(.), ]) -> (find-state-transition-for_E(.), ], right)$
[E~E{[0P>0]<[>_H<y]}P{[0E>0][_H<n]}&00^] (find-state-transition-for_E(.), [) -> (find-state-transition-for_E(.), [, right)$
[E~E{[0P>0][<_>H<y]}P{[0E>0][_H<n]}&00^] (find-state-transition-for_E(.), _) -> (retrieve-transition-to_state, _, right)$
[E~E{[0P>0][_<H><y]}P{[0E>0][_H<n]}&00^] (retrieve-transition-to_state, H) -> (retrieve-transition-H_action, H, right)$
[E~E{[0P>0][_H<<>y]}P{[0E>0][_H<n]}&00^] (retrieve-transition-H_action, <) -> (retrieve-transition-H_<_write, <, right)$
[E~E{[0P>0][_H<<y>]}P{[0E>0][_H<n]}&00^] (retrieve-transition-H_<_write, y) -> (execute-transition-H_<_y, y, right)$
[E~E{[0P>0][_H<y<]>}P{[0E>0][_H<n]}&00^] (execute-transition-H_<_y, ]) -> (execute-transition-H_<_y, ], right)$
[E~E{[0P>0][_H<y]<}>P{[0E>0][_H<n]}&00^] (execute-transition-H_<_y, }) -> (execute-transition-H_<_y, }, right)$
[E~E{[0P>0][_H<y]}<P>{[0E>0][_H<n]}&00^] (execute-transition-H_<_y, P) -> (execute-transition-H_<_y, P, right)$
[E~E{[0P>0][_H<y]}P<{>[0E>0][_H<n]}&00^] (execute-transition-H_<_y, {) -> (execute-transition-H_<_y, {, right)$
[E~E{[0P>0][_H<y]}P{<[>0E>0][_H<n]}&00^] (execute-transition-H_<_y, [) -> (execute-transition-H_<_y, [, right)$
[E~E{[0P>0][_H<y]}P{[<0>E>0][_H<n]}&00^] (execute-transition-H_<_y, 0) -> (execute-transition-H_<_y, 0, right)$
[E~E{[0P>0][_H<y]}P{[0<E>>0][_H<n]}&00^] (execute-transition-H_<_y, E) -> (execute-transition-H_<_y, E, right)$
[E~E{[0P>0][_H<y]}P{[0E<>>0][_H<n]}&00^] (execute-transition-H_<_y, >) -> (execute-transition-H_<_y, >, right)$
[E~E{[0P>0][_H<y]}P{[0E><0>][_H<n]}&00^] (execute-transition-H_<_y, 0) -> (execute-transition-H_<_y, 0, right)$
[E~E{[0P>0][_H<y]}P{[0E>0<]>[_H<n]}&00^] (execute-transition-H_<_y, ]) -> (execute-transition-H_<_y, ], right)$
[E~E{[0P>0][_H<y]}P{[0E>0]<[>_H<n]}&00^] (execute-transition-H_<_y, [) -> (execute-transition-H_<_y, [, right)$
[E~E{[0P>0][_H<y]}P{[0E>0][<_>H<n]}&00^] (execute-transition-H_<_y, _) -> (execute-transition-H_<_y, _, right)$
[E~E{[0P>0][_H<y]}P{[0E>0][_<H><n]}&00^] (execute-transition-H_<_y, H) -> (execute-transition-H_<_y, H, right)$
[E~E{[0P>0][_H<y]}P{[0E>0][_H<<>n]}&00^] (execute-transition-H_<_y, <) -> (execute-transition-H_<_y, <, right)$
[E~E{[0P>0][_H<y]}P{[0E>0][_H<<n>]}&00^] (execute-transition-H_<_y, n) -> (execute-transition-H_<_y, n, right)$
[E~E{[0P>0][_H<y]}P{[0E>0][_H<n<]>}&00^] (execute-transition-H_<_y, ]) -> (execute-transition-H_<_y, ], right)$
[E~E{[0P>0][_H<y]}P{[0E>0][_H<n]<}>&00^] (execute-transition-H_<_y, }) -> (execute-transition-H_<_y, }, right)$
[E~E{[0P>0][_H<y]}P{[0E>0][_H<n]}<&>00^] (execute-transition-H_<_y, &) -> (execute-transition-H_<_y, &, right)$
[E~E{[0P>0][_H<y]}P{[0E>0][_H<n]}&<0>0^] (execute-transition-H_<_y, 0) -> (execute-transition-H_<_y, 0, right)$
[E~E{[0P>0][_H<y]}P{[0E>0][_H<n]}&0<0>^] (execute-transition-H_<_y, 0) -> (execute-transition-H_<_y, 0, right)$
[E~E{[0P>0][_H<y]}P{[0E>0][_H<n]}&00<^>] (execute-transition-H_<_y, ^) -> (HALT, y, left)$
[E~E{[0P>0][_H<y]}P{[0E>0][_H<n]}&0<0>y] Final state reached !$
Interpreter closing...$'
}