name: Erlang CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: erlang:24.2
    steps:
      - uses: actions/checkout@v2

      - name: Compile
        run: rebar3 compile

      - name: Run unit tests
        run: rebar3 eunit

      - name: Build
        run: rebar3 escriptize

      - name: Apt-get udpate
        run: apt-get update

      - name: Install lsof
        run: apt-get -y install lsof

      - name: Run integrations tests
        run: ./bats-core/bin/bats test
